# #%L
# wcm.io
# %%
# Copyright (C) 2014 wcm.io
# %%
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# #L%
#

language: java

jdk:
- openjdk8
- openjdk11

# Make sure travis can use container-based infrastructure
sudo: false

# Switch back to Maven 3.6.1 due to https://github.com/mojohaus/build-helper-maven-plugin/issues/81
before_install:
- wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
- unzip -qq apache-maven-3.6.1-bin.zip
- export M2_HOME=$PWD/apache-maven-3.6.1
- export PATH=$M2_HOME/bin:$PATH

install: "mvn -s ./.travis.maven-settings.xml clean"

script:
- "mvn -s ./.travis.maven-settings.xml -Pcontinuous-integration -U install"
# Remove wcm.io artefacts from repository before cache
- rm -rf $HOME/.m2/repository/io/wcm

# exclude release tags like xyz.xyz-1.0.0 or xyz-xyz-1
branches:
  except:
    - /^.+(\.|\-).+\-\d+(\.\d+\.\d+)?(\..*|\-.*)?$/

# Cache Maven Repository
cache:
  directories:
  - '$HOME/.m2/repository'

# this will not work yet with a google groups mailing list - see https://github.com/travis-ci/travis-ci/issues/2513
#notifications:
#  email:
#    recipients:
#      - wcm-io-dev@googlegroups.com
#    on_success: change
#    on_failure: always
